FROM centos:7

Run yum install python36 -y

RUN python3 -m pip install --upgrade pip

RUN pip3 install --upgrade setuptools

RUN pip3 install scikit-learn 

RUN pip3 install numpy 

RUN pip3 install pandas 

RUN pip3 install seaborn  

RUN pip3 install matplotlib 

RUN pip3 install scipy 

RUN pip3 install open-cv

RUN pip3 install joblibs
